### PR TITLE
Improve reliability of scroll_to_view with Android 6 emulator webviews

### PR DESCRIPTION
**Pull request by jonstoneman**

### CODE REVIEW

**Comment by krukow** [comment]
@TobiasRoikjer please review this early next week

**Comment by TobiasRoikjer** [comment]
@jonstoneman Looks great

**Comment by jonstoneman** [comment]
@TobiasRoikjer Would the server ever be expected to handle multiple `scroll_to_view` requests simultaneously?  If so, we should probably modify `Actions.lookup()` to return a new instance of `ScrollToView` each time.

**Comment by TobiasRoikjer** [comment]
@jonstoneman I would not worry about that. This PR would not be the only thing not conforming to that!

**Pull request merged**
