### PR TITLE
Fix coordinates

### PR DESCRIPTION
**Pull request by TobiasRoikjer**
This PR should fix flaky queries.

### CODE REVIEW

**Comment by sapieneptus** [comment]
Travis is giving us a false sense of security I think :p 
@TobiasRoikjer @jmoody Would you guys mind if we prioritized creating an integration test as part of Travis before merging any more PRs (i.e., kick off XTC job)? 

Alternatively, it'd be nice to see an XTC run demonstrating that a given PR is working.   I think that's especially important given @jmoody and myself aren't as familiar with this codebase.

**Comment by TobiasRoikjer** [comment]
@sapieneptus Are you sure we are getting false positives?

**Comment by jmoody** [comment]
I agree with Chris.

* We can try the Android emulator on Travis, but my guess is that it won't be stable.
* The Android repos should submit an async test cloud job.

**Comment by sapieneptus** [comment]
@TobiasRoikjer I don't mean false positives, I mean Travis is all green and pretty, but in reality it just means the project compiles. It would be nice to be more rigid in having travis actually run tests so we can have reasonable certainty that the new features are working and don't cause unanticipated regressions. 

@jmoody I'd actually vote to try the travis emulator first. A synchronous run would be much preferable to async. Of course I have my doubts that a simulated simulator will be stable, but I'd say it's worth a shot.

**Pull request merged**
