### PR TITLE
ClearText.java use editable.clear() instead of connection.setText()

### PR DESCRIPTION
**Pull request by sapieneptus**

### CODE REVIEW

**Comment by jmoody** [comment]
> I'm OK with merging but we should test this: create a small app with a callback registered and verify that callbacks get called the same way as in the previous implementation

After reviewing #641, it looks like the TODO here is to create a test in a sample application.

**Comment by sapieneptus** [comment]
@TobiasRoikjer Why is this closed? It's probably already fine as-is, but it's just missing tests, which I will get to

**Comment by TobiasRoikjer** [comment]
@sapieneptus I did not actively close anything :)

**Comment by sapieneptus** [comment]
I see. Well, I see a few PRs were 'passively' merged then :p 

I guess we'll have to re-do them, since git now thinks they have "nothing in common with branch 'develop' "

**Pull request closed without merging**
